const PERMISSIONS = Object.freeze({
  VIEW_PROJECT: "VIEW_PROJECT",
  VIEW_TASK: "VIEW_TASK",
  VIEW_EMPLOYEE: "VIEW_EMPLOYEE",
  VIEW_WORKLOAD: "VIEW_WORKLOAD",
  VIEW_RISK: "VIEW_RISK",
  UPDATE_TASK: "UPDATE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK"
});

module.exports = {
  PERMISSIONS
};